server:
  port: 8000
#  context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xmo_demo?useUnicode:true&amp;characterEncoding:utf8
    username: root
    password: 123456
  cache:
    type: redis

#druid datasource
druid:
  initialSize: 10
  minIdle: 10
  maxActive: 50
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 'x' FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  filters: wall,stat

# mybatis
mybatis:
  type-aliases-package: com.**.model
  mapper-locations: classpath*:com/**/mapper/*.xml
  config-location: classpath:config/mybatis-config.xml
